site_name: "Kurikulum Pembelajaran Fisika"
#site_url: https://sourcefoundry.org/cinder/
site_author: "Prof. Drs. Suparwoto, M.Pd.(Pembuat Materi) dan Ilham Luqman Hadi (Web Conversion)"
site_description: "Ringkasan materi mata kuliah Kurikulum Pembelajaran Fisika tahun 2022"
#repo_url: "https://github.com/chrissimpkins/cinder"
#copyright: "Cinder is licensed under the <a href='https://github.com/chrissimpkins/cinder/blob/master/LICENSE.md'>MIT license</a>"

theme:
  name: null
  custom_dir: cinder
  colorscheme: github
  highlightjs: true

nav:
  - Home: index.md
  - Materi: materi.md

markdown_extensions:
  - mdx_math
  - admonition
  - toc:
      permalink: true

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML